### ISSUE TITLE
yk, the discord button...

### ISSUE THREAD

**Issue by Zyztem** [prozilla-os/Bliss-radio-app#1]
yea, it still leads to the xeno discord.

**Comment by Prozilla** [comment]
Where did you see this Discord button? I don’t see any Discord button anywhere.

**Comment by Zyztem** [comment]
Footer, on the website

**Comment by meFqulted** [comment]
Crazy! I didn’t notice. I’ll go ahead and change that for you, thanks for bringing that to our notice!

**Comment by Prozilla** [comment]
Pretty sure you are talking about the Bliss Radio website. This is not the right place for that, this is the Bliss Radio app for ProzillaOS. Let's discuss this further elsewhere.
